### PR TITLE
Fix. Confusion with the stats plugin

### PR DESCRIPTION
**Pull request by nivcoo**

### CODE REVIEW

**Comment by PHPierrre** [comment]
Any plan to future plugin ?

**Comment by nivcoo** [comment]
Other plugin or the one?

**Comment by PHPierrre** [comment]
Another plugin

**Comment by nivcoo** [comment]
Why ?

**Comment by PHPierrre** [comment]
Because it's strange to wake up a morning and would modify this work which works.
Btw accepted when update system gonna be operational.

**Comment by nivcoo** [comment]
So yes it works but it comes into confusion with an older plugin so we must change the one and not the other. BTW, You can accept it now there is no table change and I did not increase the version

**Comment by PHPierrre** [comment]
Smart guy, done

**Comment by nivcoo** [comment]
And I also made sure that the view of the plugin is not to change.

**Pull request merged**
